version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 231703
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build: ./TheNews-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    build: ./TheNews-frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: proxy
    build: ./.nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443